### ISSUE TITLE
No support for multiple parallel retrieve_dependencies() calls.

### ISSUE THREAD

**Issue by jehon** [brillout/website-dependency-tree#2]
I have more than two files depending on the same files, and that cause the following problem:

Here is the error message:

/home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/code-class.js:73
                throw new Error([
                ^

Error: No support for multiple parallel retrieve_dependencies() calls. Yet a second parallel call is being executed on /home/jehon/src/cryptomedic/www/bower_components/iron-meta/iron-meta.html. Run the second call sequentially instead.
    at CodeInfo.retrieve_dependencies (/home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/code-class.js:73:23)
    at /home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/workers/dependency.js:22:29
    at Array.map (native)
    at recurse (/home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/workers/dependency.js:18:10)
    at run_worker (/home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/code-class.js:182:17)
    at /home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/code-class.js:184:21
    at handle_js (/home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/workers/retrievers/requirejs.js:74:9)
    at run_worker (/home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/code-class.js:182:17)
    at /home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/code-class.js:184:21
    at /home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/workers/retrievers/requirejs.js:41:9
    at Object.done (/home/jehon/src/offline-listing/node_modules/website-dependency-tree/lib/workers/retrievers/requirejs.js:59:13)
    at /home/jehon/src/offline-listing/node_modules/jsdom/lib/jsdom.js:259:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The fact is that theses files are included from my bower dependendies, and that I can't modify them.

**Comment by jehon** [comment]
I think that in lib/code-class.js, on line 73-76, you throw an error if a dependency is already fetching.

I think that you should not throw an error, but just skip that retreiving silently.

What should be the purpose of the Error?
